
<div class="modal-footer">
    <?php if (!empty($this->noButtonLabel)): ?>
    <button
        id="<?=$this->modalName?>-dismiss"
        type="button"
        class="btn btn-default btn-modal-dismiss"
        data-dismiss="modal"
    ><?=$this->noButtonLabel?></button>
    <?php endif;?>
    <?php if (!empty($this->yesButtonLabel)): ?>
    <button
        id="<?=$this->modalName?>-save"
        <?php if (!empty($this->redirectUrl)): ?>
        data-redirect-url="<?=$this->redirectUrl?>"
        <?php endif;?>
        <?php if (!empty($this->onClickEvent)): ?>
        onClick="<?=$this->onClickEvent?>"
        <?php endif;?>
        type="button" class="btn btn-primary btn-modal-save"
    ><?=$this->yesButtonLabel?></button>
    <?php endif;?>
</div>