<div class="input-group" style="display: flex; align-items: center;">
    <div style="padding-right: 10px;"><?=$this->translate('From today +')?></div>
    <select id="expiry-handling-select" class="form-control input-sm" style="width: 150px;">
        <option value="1m"><?=$this->translate('Select 1 Month')?></option>
        <option value="3m"><?=$this->translate('Select 3 Month')?></option>
        <option value="6m"><?=$this->translate('Select 6 Month')?></option>
        <option value="1y"><?=$this->translate('Select 1 Year')?></option>
        <option value="2y"><?=$this->translate('Select 2 Year')?></option>
    </select>
</div>