<h1>Datenschutzerklärung</h1>
<p>Diese Website (nachfolgend „<strong>Website</strong>“) wird bereitgestellt von <strong>Bayer Business Services GmbH</strong> (nachfolgend „uns“ oder „wir“). Weitere Informationen zum Anbieter der Website finden Sie in unserem <a href="<?=$this->url('static', ['action' => 'imprint'])?>">Impressum</a>.</p>
<h2>Umgang mit personenbezogenen Daten </h2>
<p>Im Folgenden möchten wir Sie über unseren Umgang mit personenbezogenen Daten bei der Nutzung dieser Website informieren. Soweit in den folgenden Abschnitten nicht anders beschrieben, folgt die Rechtsgrundlage für einen Umgang mit Ihren personenbezogenen Daten aus der Erforderlichkeit eines Umgangs für die Bereitstellung der auf dieser Website von Ihnen angefragten Funktionalitäten (Art. 6(1)(b) Datenschutz-Grundverordnung).</p>
<h2>Nutzung der Website</h2>
<h3>Aufruf der Website</h3>
<p>Wenn Sie unsere Website aufrufen, überträgt Ihr Browser technisch bedingt bestimmte Informationen an unseren Webserver, um Ihnen die von Ihnen aufgerufenen Informationen zur Verfügung zu stellen. Um Ihnen den Besuch der Website zu ermöglichen, werden dabei folgende Informationen erhoben, kurzfristig gespeichert und verwendet:</p>
<ul>
    <li>IP-Adresse</li>
    <li>Datum und Uhrzeit der Anfrage</li>
    <li>Zeitzonendifferenz zur Greenwich Mean Time (GMT)</li>
    <li>Inhalt der Anforderung (konkrete Seite) </li>
    <li>Betriebssystem und dessen Oberfläche</li>
    <li>Zugriffsstatus / HTTP-Statuscode</li>
    <li>Übertragene Datenmenge </li>
    <li>Website, von der die Anforderung kommt </li>
    <li>Browser, Sprache und Version der Browsersoftware </li>
</ul>
<p>Zum Schutz unserer berechtigten Interessen werden wir die o.g. Angaben für eine begrenzte Zeit speichern, um im Falle eines unberechtigten Zugriffs oder Zugriffsversuchs auf unsere Server eine Herleitung der personenbezogen Daten veranlassen zu können(Art. 6(1)(f) Daten-schutz-Grundverordnung).</p>
<h2>Registrierung und Login</h2>
<p>Wenn Sie bestimmte Dienste unserer Website nutzen möchten, müssen Sie sich bei uns registrieren. Sie legen ein Kundenkonto an, in dem Sie Ihre persönlichen Login-Daten zur Anmeldung auf der Website festlegen. Im Rahmen der Registrierung und des Anmeldevorgangs erheben wir die folgenden Angaben über Sie:</p>
<ul>
    <li>Vor- und Nachname</li>
    <li>Kontaktdaten (einschließlich E-Mail-Adresse und Telefonnummer)</li>
</ul>
<p>Diese personenbezogenen Daten verarbeiten wir, um Ihnen den Zugang zu unserer Website und den darin enthaltenen Diensten zu ermöglichen. Sollten Sie Ihr Nutzerkonto deaktivieren, werden diese personenbezogenen Daten gelöscht.</p>
<h2>Nutzung der Login-Dienste Dritter / Single Sign-on</h2>
<p>Ihre Einwilligung vorausgesetzt (Art. 6(1)(a) Datenschutz-Grundverordnung), bieten wir Ihnen die Möglichkeit, sich über Bayer (via Microsoft Online), einem Drittanbieter für Login-Dienste (im Folgenden „Login-Provider“), zur Nutzung unserer Website anzumelden. Wenn Sie diesen Login-Dienst nutzen möchten, werden Sie aufgefordert, sich beim Login-Provider mit Ihren entsprechenden Anmeldedaten einzuloggen. Dabei wird Ihr Profil mit unseren Diensten verknüpft, d.h. der Login-Provider erhält die Information, dass Sie unsere Dienste nutzen und die folgenden Angaben werden automatisch an uns übermittelt:</p>
<ul>
    <li>Die Information, dass Ihre Identität vom Login-Provider authentifiziert wurde</li>
    <li>Ihre Kontaktdaten (einschl. E-Mail-Adresse)</li>
</ul>
<p>Diese Angaben werden wir nur zum Zweck der Registrierung verwenden und um Sie zu identifizieren, wenn Sie sich einloggen. Sollte der Login-Provider mehr Angaben über Sie übermitteln als wir zur Login-Verifizierung benötigen, so werden wir diese umgehend löschen. Weitere Informationen über den Dienst des Login-Providers und darüber, wie dieser Ihre personenbezogenen Daten verarbeitet, finden Sie in der <a href="https://privacy.microsoft.com/en-US/privacystatement" target="_blank">Datenschutzerklärung des Login-Providers</a>. Wir löschen Ihre personenbezogenen Daten, wenn Sie Ihr Kundenkonto bei uns löschen.</p>
<h2>Einsatz von Cookies</h2>
<h3>Was Cookies sind</h3>
<p>Auf dieser Website setzen wir so genannte „Cookies“ ein. Cookies sind kleine Textdateien, die über Ihren Browser im Speicher Ihres Endgeräts abgelegt werden. Cookies speichern bestimmte Informationen (z.B. die von Ihnen bevorzugte Sprache oder Seiteneinstellungen), die durch Ihren Browser bei einem erneuten Besuch der Website an uns zurückgesendet werden können (abhängig von der Lebensdauer des Cookies).</p>
<h3>Welche Cookies wir einsetzen</h3>
<p>Wir unterscheiden zwei Kategorien von Cookies: (1) funktionsbezogene Cookies, ohne die die Funktionalität unserer Website eingeschränkt wäre und (2) optionale Cookies, z.B. für Zwecke der Website-Analyse und des Marketings. In der folgenden Tabelle beschreiben wir die auf dieser Website eingesetzten optionalen Cookies im Detail:</p>
<h3>Optionale Cookies</h3>
<p>Diese Webseite benutzt keine optionalen cookies.</p>
<h3>Wie Sie die Nutzung von Cookies verhindern</h3>
<p>Selbstverständlich können Sie unsere Website auch ganz ohne Cookies nutzen. Sie können den Einsatz von Cookies in den Einstellungen Ihres Browsers jederzeit konfigurieren oder gänzlich deaktivieren. Dies kann jedoch zu Einschränkungen der Funktionen oder der Benutzerfreundlichkeit unseres Angebots führen.</p>
<h2>Nutzung von Kontaktformularen</h2>
<p>Über auf der Website bereitgestellte Kontaktformulare können Sie direkt mit uns in Verbindung treten. Sie haben dabei die Möglichkeit, uns insbesondere folgende Informationen mitzuteilen:</p>
<ul>
    <li>Kontaktdaten (z.B. E-Mail Adresse, Telefonnummer) </li>
    <li>Nachricht</li>
</ul>
<p>Wir verarbeiten die von Ihnen über Kontaktformulare mitgeteilten Informationen ausschließlich für die Bearbeitung Ihres konkreten Anliegens. Wir löschen diese Informationen, sobald diese für die Bearbeitung Ihrer Anfrage nicht mehr benötigt werden.</p>
<h2>Informationen über Ihre Rechte</h2>
<p>Die folgenden Rechte stehen Ihnen aufgrund der anwendbaren Datenschutzgesetze zur Verfügung:</p>
<ul>
    <li>Recht auf Auskunft über die bei uns zu Ihrer Person gespeicherten Daten;</li>
    <li>Recht auf Berichtigung, Löschung oder Einschränkung der Verarbeitung Ihrer personenbezogenen Daten;</li>
    <li>Recht auf Widerspruch gegen eine Verarbeitung, die unserem berechtigten Interesse, einem öffentlichen Interesse oder einem Profiling dient, es sei denn, wir können zwingende schutzwürdige Gründe für die Verarbeitung nachweisen, die Ihre Interessen, Rechte und Freiheiten überwiegen, oder die Verarbeitung dient der Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen;</li>
    <li>Recht auf Datenübertragbarkeit;</li>
    <li>Recht sich bei einer Aufsichtsbehörde zu beschweren;</li>
    <li>Von Ihnen erteilte Einwilligungen zur Verarbeitung Ihrer personenbezogenen Daten können Sie jederzeit mit Wirkung für die Zukunft widerrufen. Nähere Informationen hierzu finden Sie in den jeweiligen Abschnitten oben, wo eine Datenverarbeitung auf Grundlage Ihrer Einwilligung beschrieben wird</li>
</ul>
<p>Falls Sie von Ihren Rechten Gebrauch machen möchten, richten Sie bitte Ihr Anliegen an den unten genannten Ansprechpartner (siehe Kontakt).</p>
<h2>Kontakt</h2>
<p>Für Ihre Anliegen zum Datenschutz schreiben Sie <a href="<?=$this->url('static', ['action' => 'contact'])?>">bitte an uns</a> oder kontaktieren Sie unseren Konzerndatenschutzbeauftragten unter folgender Adresse: </p>
<p>
<strong>Datenschutzverantwortlicher Bayer Business Services GmbH:</strong><br />
Diana Stoll<br />
Gebäude B151<br />
D-51368 Leverkusen<br />
Tel.: +49 (0) 214 / 30 54030<br />
E-Mail: <a href="mailto:diana.stoll@bayer.com">diana.stoll@bayer.com</a><br /><br />
<strong>Head of Data Privacy: </strong><br />
Eva Gardyan-Eisenlohr <br />
Tel.: +49 (0) 30 468 16924 <br />
<a target="_blank" href="https://secure.bayer.com/bayer/ContactDataprotectionOfficer.aspx?lang=de">E-mail</a>
</p>
<h2>Anpassung der Datenschutzerklärung</h2>
<p>Wir behalten uns vor, diese Datenschutzerklärung von Zeit zu Zeit zu aktualisieren. Aktualisierungen dieser Datenschutzerklärung werden auf unserer Website veröffentlicht. Änderungen gelten ab ihrer Publikation auf unserer Website. Wir empfehlen Ihnen daher, diese Seite regelmäßig zu besuchen, um sich über gegebenenfalls erfolgte Aktualisierungen zu informieren.</p>
<p>Stand: 01.03.2020.</p>